name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello world action step
        id: hello
        run: |
          echo "Hello World!"
      - name: Current date
        id: date
        run: |
          date
      - name: File list
        id: files
        run: |
          ls -l